<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $mode === 'register' ? 'Buat akun' : 'Masuk' }} · Toko Nadhim Alim</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="{{ asset('css/marketplace.css') }}?v=7"><link rel="stylesheet" href="{{ asset('css/feedback.css') }}?v=1"></head>
<body><header class="shop-nav"><a class="shop-brand" href="{{ route('marketplace.index') }}">NA<span>.</span></a><span class="checkout-steps"><i class="bi bi-shield-lock"></i> Akun pelanggan</span><a class="shop-nav-back" href="{{ route('marketplace.cart') }}"><i class="bi bi-arrow-left"></i> Keranjang</a></header>
<main class="shop-wrap account-page"><section class="account-card"><span class="shop-kicker">TOKO NADHIM ALIM</span><h1>{{ $mode === 'register' ? 'Buat akun pelanggan' : 'Selamat datang kembali.' }}</h1><p>{{ $mode === 'register' ? 'Daftar sekali untuk checkout dan memantau pesanan Anda.' : 'Masuk untuk melanjutkan checkout dan melihat pesanan.' }}</p>
@if(session('success'))<div class="shop-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="shop-error" role="alert">{{ $errors->first() }}</div>@endif
<form class="account-form" action="{{ $mode === 'register' ? route('marketplace.account.store') : route('marketplace.account.authenticate') }}" method="POST" data-loading-title="{{ $mode === 'register' ? 'Membuat akun...' : 'Memeriksa akun...' }}" data-loading-description="Mohon tunggu sebentar.">@csrf
@if($mode === 'register')<label>Nama lengkap<input name="name" required maxlength="120" autocomplete="name" value="{{ old('name') }}" placeholder="Nama Anda"></label>@endif
<label>Email<input type="email" name="email" required maxlength="255" autocomplete="email" value="{{ old('email') }}" placeholder="nama@email.com"></label><label>Kata sandi<input type="password" name="password" required @if($mode === 'register') minlength="8" @endif autocomplete="{{ $mode === 'register' ? 'new-password' : 'current-password' }}" placeholder="{{ $mode === 'register' ? 'Minimal 8 karakter' : 'Kata sandi akun' }}"></label>
@if($mode === 'register')<label>Ulangi kata sandi<input type="password" name="password_confirmation" required minlength="8" autocomplete="new-password" placeholder="Masukkan kembali kata sandi"></label>@else<label class="account-remember"><input type="checkbox" name="remember" value="1"> Tetap masuk di perangkat ini</label>@endif
<button class="shop-buy-button" type="submit">{{ $mode === 'register' ? 'Buat akun' : 'Masuk' }} <i class="bi bi-arrow-right"></i></button></form>
<div class="account-switch">{{ $mode === 'register' ? 'Sudah punya akun?' : 'Belum punya akun?' }} <a href="{{ route($mode === 'register' ? 'marketplace.account.login' : 'marketplace.account.register') }}">{{ $mode === 'register' ? 'Masuk' : 'Daftar sekarang' }}</a></div><a class="checkout-return" href="{{ route('marketplace.index') }}">Kembali ke toko</a></section></main><script src="{{ asset('js/feedback.js') }}" defer></script></body></html>
