<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Keranjang belanja · Nadhim Alim</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="{{ asset('css/marketplace.css') }}?v=8"><link rel="stylesheet" href="{{ asset('css/feedback.css') }}?v=1"></head>
<body>@php($cartCount = collect(session('marketplace_cart', []))->sum())
<header class="shop-nav"><a class="shop-brand" href="{{ route('home') }}">NA<span>.</span></a><form class="shop-search" action="{{ route('marketplace.index') }}" method="GET"><input type="search" name="q" placeholder="Cari barang lain..." aria-label="Cari barang"><button type="submit" aria-label="Cari"><i class="bi bi-search"></i></button></form><a class="shop-cart-link active" href="{{ route('marketplace.cart') }}"><i class="bi bi-bag"></i><span>Keranjang</span><b>{{ $cartCount }}</b></a><a class="shop-nav-back" href="{{ route('marketplace.index') }}"><i class="bi bi-arrow-left"></i> Belanja</a></header>
<main class="shop-wrap cart-page"><div class="cart-page-title"><div><span class="shop-kicker">PESANANMU</span><h1>Keranjang belanja</h1><p>Periksa barang dan jumlahnya sebelum lanjut ke checkout.</p></div><a href="{{ route('marketplace.index') }}"><i class="bi bi-plus-lg"></i> Tambah barang lain</a></div>
    @if(session('cart_success'))<div class="shop-success"><i class="bi bi-check-circle"></i> {{ session('cart_success') }}</div>@endif
    @if($errors->any())<div class="shop-error" role="alert">{{ $errors->first() }}</div>@endif
    @if($cartItems->isEmpty())<section class="cart-empty"><span><i class="bi bi-bag"></i></span><h2>Keranjangmu masih kosong.</h2><p>Yuk, lihat barang yang tersedia di toko.</p><a class="shop-buy-button" href="{{ route('marketplace.index') }}">Mulai belanja <i class="bi bi-arrow-right"></i></a></section>
    @else<div class="cart-layout"><section class="cart-items-panel"><div class="cart-items-heading"><strong>Barang dipilih</strong><span>{{ $cartCount }} barang</span></div>@foreach($cartItems as $item)<article class="cart-item {{ !$item->available ? 'unavailable' : '' }}"><a class="cart-item-image" href="{{ route('marketplace.show', $item->product->slug) }}">@if($item->product->image)<img src="{{ asset('storage/'.$item->product->image) }}" alt="{{ $item->product->name }}">@else<i class="bi bi-bag"></i>@endif</a><div class="cart-item-info"><a href="{{ route('marketplace.show', $item->product->slug) }}">{{ $item->product->name }}</a><small>{{ $item->product->category ?: 'Barang pilihan' }} · Stok {{ $item->product->stock }}</small><strong>Rp {{ number_format($item->product->price, 0, ',', '.') }}</strong>@unless($item->available)<span class="cart-unavailable-note">Stok berubah. Sesuaikan jumlah sebelum checkout.</span>@endunless</div><div class="cart-item-actions"><form action="{{ route('marketplace.cart.update', $item->product->slug) }}" method="POST" data-loading-title="Memperbarui keranjang...">@csrf @method('PATCH')<label class="sr-only" for="quantity-{{ $item->product->id }}">Jumlah {{ $item->product->name }}</label><select id="quantity-{{ $item->product->id }}" name="quantity">@for($quantity=1; $quantity<=max(1,min(100,$item->product->stock)); $quantity++)<option value="{{ $quantity }}" @selected($quantity===$item->quantity)>{{ $quantity }}</option>@endfor</select><button class="cart-update-button" type="submit">Perbarui</button></form><form action="{{ route('marketplace.cart.remove', $item->product->slug) }}" method="POST" data-confirm="Hapus {{ $item->product->name }} dari keranjang?" data-loading-title="Menghapus barang..." data-loading-description="Barang sedang dihapus dari keranjang.">@csrf @method('DELETE')<button class="cart-remove-button" type="submit" aria-label="Hapus {{ $item->product->name }}"><i class="bi bi-trash3"></i> Hapus</button></form><strong class="cart-line-total">Rp {{ number_format($item->line_total, 0, ',', '.') }}</strong></div></article>@endforeach</section>
        <aside class="cart-summary"><span class="shop-kicker">RINGKASAN</span><h2>Total belanja</h2><div><span>Subtotal barang</span><strong>Rp {{ number_format($subtotal, 0, ',', '.') }}</strong></div><div><span>Ongkos kirim</span><strong>{{ $shippingConfigured ? 'Dihitung dari wilayah tujuan' : 'Tarif segera tersedia' }}</strong></div><div class="cart-summary-total"><span>Subtotal sementara</span><strong>Rp {{ number_format($subtotal, 0, ',', '.') }}</strong></div><a class="shop-buy-button" href="{{ route('marketplace.checkout.cart') }}">Lanjut ke checkout <i class="bi bi-arrow-right"></i></a><small><i class="bi bi-shield-check"></i> Ongkir dan total final ditampilkan setelah wilayah tujuan dipilih.</small></aside></div>@endif
</main><footer class="shop-footer"><a href="{{ route('marketplace.index') }}">← Lanjut belanja</a><span>NA<span>.</span> · Marketplace</span></footer><script src="{{ asset('js/feedback.js') }}" defer></script></body></html>
