<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $product->name }} · Toko Nadhim Alim</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="{{ asset('css/marketplace.css') }}?v=6"><link rel="stylesheet" href="{{ asset('css/feedback.css') }}?v=1"></head>
<body>
@php($cartCount = collect(session('marketplace_cart', []))->sum())
<header class="shop-nav"><a class="shop-brand" href="{{ route('home') }}">NA<span>.</span></a><form class="shop-search" action="{{ route('marketplace.index') }}" method="GET"><input type="search" name="q" placeholder="Cari barang lain..." aria-label="Cari barang"><button type="submit" aria-label="Cari"><i class="bi bi-search"></i></button></form><a class="shop-cart-link" href="{{ route('marketplace.cart') }}"><i class="bi bi-bag"></i><span>Keranjang</span>@if($cartCount)<b>{{ $cartCount }}</b>@endif</a><a class="shop-nav-back" href="{{ route('marketplace.index') }}"><i class="bi bi-arrow-left"></i> Kembali ke toko</a></header>
<main class="shop-wrap product-page"><div class="product-breadcrumb"><a href="{{ route('marketplace.index') }}">Toko</a> <i class="bi bi-chevron-right"></i> {{ $product->category ?: 'Detail barang' }} <i class="bi bi-chevron-right"></i> {{ $product->name }}</div>
    @if(session('cart_success'))<div class="shop-success"><i class="bi bi-check-circle"></i> {{ session('cart_success') }} <a href="{{ route('marketplace.cart') }}">Lihat keranjang</a></div>@endif
    <div class="product-detail-grid"><div class="product-detail-gallery"><div class="product-thumbnails"><div class="product-thumbnail">@if($product->image)<img src="{{ asset('storage/'.$product->image) }}" alt="">@else<i class="bi bi-bag"></i>@endif</div></div><div class="product-detail-image">@if($product->image)<img src="{{ asset('storage/'.$product->image) }}" alt="{{ $product->name }}">@else<div class="shop-image-placeholder"><i class="bi bi-bag"></i></div>@endif</div></div>
        <article class="product-detail-copy"><span class="shop-kicker">{{ $product->category ?: 'BARANG PILIHAN' }}</span><h1>{{ $product->name }}</h1><strong class="product-price">Rp {{ number_format($product->price, 0, ',', '.') }}</strong><p class="product-description">{{ $product->description }}</p><div class="product-stock"><i class="bi bi-box-seam"></i>{{ $product->stock > 0 ? $product->stock.' tersedia' : 'Stok sedang habis' }}</div>
            @if($errors->any())<div class="shop-error" role="alert">{{ $errors->first() }}</div>@endif
            @if($product->stock > 0)
                <form class="shop-order-form" action="{{ route('marketplace.cart.add', $product->slug) }}" method="POST" data-loading-title="Menambahkan barang..." data-loading-description="Memperbarui keranjang belanja Anda.">@csrf<h2>Pilih jumlah</h2><label>Jumlah barang<select name="quantity">@for($quantity=1; $quantity<=min(20,$product->stock); $quantity++)<option value="{{ $quantity }}" @selected(old('quantity',1)==$quantity)>{{ $quantity }} barang</option>@endfor</select></label><button class="shop-buy-button" type="submit"><i class="bi bi-bag-plus"></i> Tambahkan ke keranjang</button><a class="shop-secondary-link" href="{{ route('marketplace.cart') }}">Lanjut ke keranjang <i class="bi bi-arrow-right"></i></a><small class="shop-safe-note"><i class="bi bi-shield-lock"></i> Pembayaran dilakukan sekaligus saat checkout.</small></form>
            @else
                <div class="sold-out-note">Barang ini sedang habis. Silakan cek kembali nanti.</div>
            @endif
        </article>
    </div>
</main><footer class="shop-footer"><a href="{{ route('marketplace.index') }}">← Kembali ke toko</a><span>NA<span>.</span> · Marketplace</span></footer><script src="{{ asset('js/feedback.js') }}" defer></script></body></html>
